### ISSUE TITLE
Standardize properties cases

### ISSUE THREAD

**Issue by chrisnuval** [xendit/xendit-node#156]
In https://developers.xendit.co/api-reference/#create-invoice , parameters in snake_case (such as _external_id_) are provided.
But looking into https://github.com/xendit/xendit-node/blob/master/src/invoice/invoice.d.ts#L9 , we are saying that the property is _externalID_.

Issues might arise with the inconsistency when we wrap the service and create a request

```
import { InvoiceService } from 'xendit-node/src/invoice';
.
.
.
export class InvoiceAPIWrapper {
    private client: InvoiceService;
.
.
.
  constructor(client: InvoiceService, options: XenditOptions) {
      this.client = client;
      this.options = options;
  }

  public create(
      invoice?: Invoice
  ): Cypress.Chainable<Cypress.Response<CreateInvoiceResponse>> {

      const requestBody = update(apiData.invoice, invoice || {});
      return doAsync(() => this.client.createInvoice(requestBody));
  }
```

Wherein the request body is expected to be
```
.
.
.
export const apiData = {
    invoice: {
        externalID:'someId',
        payerEmail:'some@email.com',
        amount: 10000,
        shouldSendEmail: false,
        description: 'some description'
    }
.
.
.
```

But when the request is sent, we'll get an error 400 since external_id is required.

Others:
In https://github.com/xendit/xendit-node/blob/master/src/invoice/invoice.js#L47:L69 , we're using _external_id_ to POST a request.

**Comment by MESMUR** [comment]
The reason for this is that our API standard for parameters use snake case (external_id) in designing the APIs but our code standards use camel case (externald) in implementing the logic. It's an intentional choice and something we're unlikely to standardize because they serve their own purposes.

I don't think there will be much confusion. If you're wrapping a request to hit and endpoint directly you will be following the API standards (snake case) and if you use the SDK to wrap your request you'll follow _our_ code standards which would be camel case (and we wrap the request for you).

**Comment by chrisnuval** [comment]
Given this is clarified, I can close the issue @MESMUR.
