### ISSUE TITLE
QRCode cant create

### ISSUE THREAD

**Issue by diarmp** [xendit/xendit-node#193]
please change external_id to reference_id in function QR create code

because make error:

 {
    "status": 400,
    "code": "API_VALIDATION_ERROR",
    "message": "Failed to validate the request, 1 error occurred."
}

**Comment by adityarx** [comment]
@diarmp we are currently only supporting [V1 QR code creation ](https://developers.xendit.co/api-reference/qr-codes/#create-qr-code)through the SDK at the moment. Apologies, we are unfortunately unable to provide support for V2 SDKs due to a resourcing constraint. 

Our QR team recommends you use the API instead or if you'd like to raise a PR with support for V2 QR codes, we're happy to review it.
