### ISSUE TITLE
QR Code request Headers

### ISSUE THREAD

**Issue by abduljafars** [xendit/xendit-node#206]
Hi Team,

Can help to add request header parameter for the create QrCode method(https://github.com/xendit/xendit-node#qr-code-services), Since there are two versions available, so in order to use the latest version user has to explicitly set in the request headers with proper version. 

Can refer to the latest document : https://developers.xendit.co/api-reference/#create-qr-code
<img width="1426" alt="Screenshot 2023-08-29 at 3 25 52 PM" src="https://github.com/xendit/xendit-node/assets/19304040/86e0a9df-e37e-4b86-bf7f-79eeaee5f5d5">

**Comment by adityarx** [comment]
Hi @abduljafars, unfortunately this is not supported through the SDK at the moment. We do however support the V2 QR API through the Payments API.

We have a new version of SDKs releasing in the next couple of weeks that should have the Payments API available. Would you be interested to wait for that?

Alternatively, we can recommend you to use the API directly instead of using the SDK

**Comment by abduljafars** [comment]
> Hi @abduljafars, unfortunately this is not supported through the SDK at the moment. We do however support the V2 QR API through the Payments API.
> 
> We have a new version of SDKs releasing in the next couple of weeks that should have the Payments API available. Would you be interested to wait for that?
> 
> Alternatively, we can recommend you to use the API directly instead of using the SDK

Thanks for the update.
I will use the API instead of SDK.
